const $=s=>document.querySelector(s),worker=new Worker('./worker.js',{type:'module'});let ready=false,request=0,timer,result;
const labels=['Task intent','Search design','Validation plan','Interface notes','Supporting evidence'];
for(const side of ['left','right'])for(const[i,text]of labels.entries()){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.id=`${side}-${i}`;input.disabled=true;input.checked=side==='left'?i<2:i===1||i===2;input.onchange=calculate;label.append(input,document.createTextNode(text));$(`#${side}`).append(label);}
const mask=side=>labels.reduce((value,_,i)=>value|($(`#${side}-${i}`).checked?1<<i:0),0);
function calculate(){request++;clearTimeout(timer);$('#budget-value').textContent=$('#budget').value;$('#export').disabled=true;if(!ready)return;$('#status').textContent='Closing context…';timer=setTimeout(()=>worker.postMessage({id:request,left:mask('left'),right:mask('right'),budget:Number($('#budget').value),operation:$('#operation').value}),80);}
function fail(message){result=null;$('#status').textContent=message;$('#verdict').textContent='Cannot close context';$('#export').disabled=true;$('#retained').replaceChildren();$('#frontier').replaceChildren();$('#inputs').textContent='';$('#receipt').textContent='';for(const id of ['grains','bonds','deferred'])$(`#${id}`).textContent='—';$('#none').hidden=true;}
worker.onerror=()=>fail('Context engine could not load. Reload to retry or read the source.');
worker.onmessage=({data})=>{if(data.type==='ready'){ready=true;document.querySelectorAll('input,select,button').forEach(e=>e.disabled=false);calculate();return;}if(data.id!==undefined&&data.id!==request)return;if(data.type==='error'){fail(ready?data.message:'Context engine could not load. Reload to retry or read the source.');return;}result=data.result;const r=result.result,entries=[...result.left.frontier.map(v=>['A',v]),...result.right.frontier.map(v=>['B',v]),...r.frontier.map(v=>['Combined',v])];$('#grains').textContent=r.grain_count;$('#bonds').textContent=r.bond_count;$('#deferred').textContent=entries.length;$('#verdict').textContent=entries.length?'Closed with deferred work':'Closed within budget';$('#inputs').textContent=`Context A retains ${result.left.grain_count} grains; B retains ${result.right.grain_count}.`;$('#status').textContent=`Synthetic ${result.operation} · ${data.ms.toFixed(1)} ms · processing stays on your device`;$('#retained').replaceChildren();for(const grain of r.grains){const card=document.createElement('div');card.className='grain';card.textContent=grain.label;const kind=document.createElement('small');kind.textContent=grain.kind.replaceAll('_',' ');card.append(kind);$('#retained').append(card);}$('#frontier').replaceChildren();for(const[stage,item]of entries){const li=document.createElement('li');li.textContent=`${stage}: ${item.note} (${item.item})`;$('#frontier').append(li);}$('#none').hidden=entries.length>0;$('#receipt').textContent=JSON.stringify({cut_hash:r.cut_hash,receipt_hash:r.receipt_hash,receipts:r.receipts},null,2);$('#export').disabled=false;};
$('#budget').oninput=calculate;$('#operation').onchange=calculate;$('#reset').onclick=()=>{$('#budget').value='8';$('#operation').value='join';for(let i=0;i<5;i++){$(`#left-${i}`).checked=i<2;$(`#right-${i}`).checked=i===1||i===2;}history.replaceState(null,'',location.pathname);calculate();};
$('#share').onclick=async()=>{const url=new URL(location.href);url.search='';for(const side of ['left','right'])url.searchParams.set(side,mask(side));url.searchParams.set('budget',$('#budget').value);url.searchParams.set('operation',$('#operation').value);history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url.href);}catch{}$('#status').textContent='Selection link is in the address bar.';};$('#export').onclick=()=>{if(!result)return;const inputs={left:mask('left'),right:mask('right'),budget:Number($('#budget').value),operation:$('#operation').value};const url=URL.createObjectURL(new Blob([JSON.stringify({inputs,result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lattice-synthetic-algebra.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const params=new URLSearchParams(location.search);for(const side of ['left','right']){const n=Number(params.get(side));if(params.has(side)&&Number.isInteger(n)&&n>=0&&n<=31)for(let i=0;i<5;i++)$(`#${side}-${i}`).checked=Boolean(n&(1<<i));}const budget=Number(params.get('budget'));if(params.has('budget')&&Number.isInteger(budget)&&budget>=1&&budget<=8)$('#budget').value=budget;if(['meet','join'].includes(params.get('operation')))$('#operation').value=params.get('operation');worker.postMessage({type:'init'});
